server:
  port: 8003
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zuulServer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/yu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
security:
  oauth2:
    client:
      client-id: zuul
      client-secret: 123456
      access-token-uri: http://localhost:8002/oauth/token
      user-authorization-uri: http://localhost:8002/oauth/authorize
      client-authentication-scheme: form
      use-current-uriestablished: false
      pre--redirect-uri: /login
    resource:      #这配配置的是服务器的地址
      token-info-uri: 'http://127.0.0.1:8002/oauth/check_token'


